### ISSUE TITLE
Missing option to add Entities to different Configurations

### ISSUE THREAD

**Issue by vander2675** [dmytro-anokhin/core-data-model-description#1]
Hey, 
Very nice package! I immediately jumped on it because I wanted to extract my Persistence into a Swift Package.

I found that there is no option to define the Configurations in wich entities are present. I think this would be a nice feature to add.

I can help if needed.

**Comment by dmytro-anokhin** [comment]
Hey,

glad that you find the package useful. Configurations are indeed missing. Help is appreciated so feel free to create a pull request.

Cheers

**Comment by dmytro-anokhin** [comment]
Included in v0.0.2. Thank you for contribution.
