### ISSUE TITLE
Add support for default values to attributes

### ISSUE THREAD

**Issue by mrlegowatch** [dmytro-anokhin/core-data-model-description#5]
I tried using this to replace an existing project xcdatamodeld, and found that default values are missing. On the bright side, I determined that the default values are actually bad for my specific use case, so I don't need it. However, I figured I would flag it here, in case someone does depend on default values for attributes.

**Comment by dmytro-anokhin** [comment]
Implemented by @elisa-laviolette in 0.0.6
